- name: Domain Controller creation
  hosts: domain_controllers
  serial: 1
  tasks:
    - name: create or join domain controller
      win_domain:
        dns_domain_name: tform.test
        safe_mode_password: "password123!"
      register: reboot_check
    - name: check if reboot is needed
      win_reboot:
      when: reboot_check.reboot_required
    - name: add users to domain for testing vault
      win_domain_user:
        name: "{{ item.name }}"
        upn: "{{ item.name + '@tform.test' }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password}}"
        enabled: yes
      with_items:
        - { name: 'vault01', groups: 'Domain Admins', password: 'password123!'}
        - { name: 'vault02', groups: 'Domain Users', password: 'password123!'}
        - { name: 'vault03', groups: 'Domain Users', password: 'password123!'}