- name: Domain Controller creation
  hosts: domain_controllers
  serial: 1
  tasks:
    - name: create or join domain controller
      win_domain:
        dns_domain_name: tform.test
        safe_mode_password: "password123!"
      register: reboot_check
    - name: check if reboot is needed
      win_reboot:
      when: reboot_check.reboot_required
    - name: add users to domain for testing vault
      win_domain_user:
        name: "{{ item.name }}"
        upn: "{{ item.name + '@' + active_directory_domain }}"
        groups: "{{ item.groups }}"
      with_items:
        - { name: 'vault01', groups: 'Domain Admins'}
        - { name: 'vault02'}
        - { name: 'vault03'}
