domain_controllers:
        hosts:
            10.128.0.3
        vars:
            ansible_connection: winrm
            ansible_user: dle_pyc
            ansible_password: "replace"
            ansible_winrm_transport: basic
            ansible_winrm_server_cert_validation: ignore