domain_controllers:
    hosts:
        
    vars:
        ansible_connection: winrm
        ansible_user: dle_pyc
        ansible_password: "replace"
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore

logstash:
    hosts:
        
    vars:
        ansible_user: dle.pyc

elastic:
    hosts:
        
    vars:
        ansible_user: dle.pyc