domain_controllers:
    hosts:
        35.208.10.221
    vars:
        ansible_connection: winrm
        ansible_user: dle_pyc
        ansible_password: "replace"
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore

logstash:
    hosts:
        35.208.118.99
    vars:
        ansible_user: dle.pyc

elastic:
    hosts:
        35.208.15.124
    vars:
        ansible_user: dle.pyc

kibana:
    hosts:
        35.208.50.75
    vars:
        ansible_user: dle.pyc
