domain_controllers:
    hosts:
        10.128.0.4
    vars:
        ansible_connection: winrm
        ansible_user: dle_pyc
        ansible_password: "replace"
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore

logstash:
    hosts:
        35.208.45.254
    vars:
        ansible_user: dle.pyc
