- name: Kibana Install
  hosts: kibana
  become: yes
  tasks:
    - name: Install Java openjdk
      yum:
        name: java-1.8.0-openjdk
        state: installed

    - name: Install Public Signing Key
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Configure Yum Repo
      yum_repository:
        name: kibana-7.x
        description: Kibana repository for 7.x packages
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Kibana
      yum: 
        name: kibana
        state: latest

    - name: Start service kibana, if not started
      service:
        name: kibana
        state: started
