- name: Logstash Install
  hosts: logstash
  become: yes
  tasks:
    - name: Install Java openjdk
      yum:
        name: java-1.8.0-openjdk
        state: installed

    - name: Install Public Signing Key
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Configure Yum Repo
      yum_repository:
        name: logstash-7.x
        description: Elastic repository for 7.x packages
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install logstash
      yum: 
        name: logstash
        state: latest

    - name: Download Logstash.yml
      get_url:
        url: https://raw.githubusercontent.com/de-py/Terraform-Ansible-Demo/master/elastic/logstash.yml
        dest: /etc/logstash/logstash.yml
    
    - name: Generate Logstash Service 
      shell: /usr/share/logstash/bin/system-install /etc/logstash/startup.options systemd
