- name: Logstash Install
  hosts: logstash
  become: yes
  tasks:
    - name: Install Public Signing Key
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Configure Yum Repo
      yum_repository:
        name: logstash-7.x
        description: Elastic repository for 7.x packages
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install logstash
      yum: 
        name: logstash
        state: latest