---
# tasks file for Java
#


#- name: Install apt-transport-https
#  apt:
#      name: apt-transport-https
#      update_cache: yes
#
#- name: Install Public Signing Key
#  apt_key:
#      url: "{{ java_gpg_key }}"
#      state: present

- name: Install Java
  apt:
      name: "{{ java_version }}"
      update_cache: yes

