---
# tasks file for ELK-prereq
#
- name: Install Public Signing Key
  apt_key:
      url: "{{ elastic_gpg_key }}"
      state: present

- name: Install apt-transport-https
  apt:
      name: apt-transport-https
      update_cache: yes

- name: Add Elasticsearch Repo
  apt_repository:
      repo: deb {{ elastic_deb_repo }} stable main
      state: present

- name: Apt Update
  apt:
      update_cache: yes

